# Top-level configuration
name = "tmfcg"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir="/.output"

[vars]
NODE_VERSION = "22"
YARN_VERSION = "1.22.22"